name: Nodejs

on:
  push:
    branches:
      - master

jobs:
  build-and-scan:
    name: Build, SonarQube Scan, and Trivy Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install

     # - name: SonarQube Scan
     #   uses: sonarsource/sonarqube-scan-action@master
     #   env:
     #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
     #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          
      - name: Build and Push image to Amazon ECR
        run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            fi

  trivy-scan:
    needs: build-and-scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Trivy
        run: |
          sudo curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/install.sh | sudo sh -

      - name: Log in to Amazon ECR for Docker
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Pull image from ECR
        run: |
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}

      - name: Scan image
        run: |
          trivy image $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
