name: nodejsproj

on:
  push:
    branches:
      - master

jobs:
  code-scanning:
    name: SonarQube Code Scanning
    runs-on: ubuntu-latest
    env:
      SONAR_HOST_URL: 'http://35.154.176.88:9000'
      SONAR_LOGIN: 'squ_75fc1b22be66e108266ace8132e90d56e3d576b5'

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master

  build-and-push:
    name: Build and push image to AWS ECR
    needs: code-scanning
    runs-on: ubuntu-latest

    steps:
      # Steps for building and pushing to AWS ECR as per your existing configuration
