name: Trivy Scan

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  trivy_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Replace this with the appropriate AWS region

    - name: Install Trivy
      run: |
        AWS_ACCOUNT_ID=186453136742
        AWS_REGION=ap-south-1
        ECR_REPOSITORY=nodejs
        IMAGE_TAG="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:latest"

        trivy image --exit-code 1 --severity HIGH,CRITICAL "$IMAGE_TAG"
