name: Trivy Scan

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  trivy_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Replace this with the appropriate AWS region

    - name: Install Trivy
      run: |
        wget https://github.com/aquasecurity/trivy/releases/download/v0.19.2/trivy_0.19.2_Linux-64bit.tar.gz
        tar zxvf trivy_0.19.2_Linux-64bit.tar.gz
        sudo mv trivy /usr/local/bin/
        rm trivy_0.19.2_Linux-64bit.tar.gz

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

    - name: Pull image from ECR
      run: |
        docker pull ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

    - name: Scan Docker image with Trivy
      run: |
        trivy image ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}
